global:
  debug: true  # Whether to print debug logs in terminal
  port: 8080   # Port to listen on

crystals:
  - name: "testing"
    shards:
      # Discord example
      - alias: "Discord Notifications"
        type: "discord"
        envVar: false
        webhook: "https://discord.com/api/webhooks/..."

      # Telegram example
      - alias: "Telegram Alerts"
        type: "telegram"
        envVar: false
        webhook: "https://api.telegram.org/bot<TOKEN>/sendMessage"
        chatId: "123456789"

      # Slack example
      - alias: "Slack Logs"
        type: "slack"
        envVar: true
        webhook: "SLACK_WEBHOOK_ENV_VAR"
